# Используем официальный Python 3.12 образ
FROM python:3.12-slim

# Устанавливаем необходимые системные зависимости для Chrome и Selenium
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    unzip \
    libx11-dev \
    libx11-xcb-dev \
    libxrandr-dev \
    libglu1-mesa \
    libnss3 \
    libgdk-pixbuf2.0-0 \
    libgdk-pixbuf2.0-dev \
    libdbus-1-3 \
    libfontconfig1 \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb || apt-get -y install -f

# Устанавливаем webdriver-manager и другие зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . /app
WORKDIR /app

# Запуск приложения
CMD ["python", "main.py"]
